services:
  postgres:
    image: postgres:16
    container_name: book_index_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: book_index
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book_index_app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: book_index
      PGPASSWORD: password
      PGPORT: 5432
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-client
    environment:
      VITE_API_BASE: http://localhost:3000
    ports:
      - "4173:4173"
    depends_on:
      - app

volumes:
  db-data: